### ISSUE TITLE
[RFC] Let users write `:packadd volt` in his/her vimrc

### ISSUE THREAD

**Issue by tyru** [vim-volt/volt#118]
# TL;DR

Volt の仕様変更で vimrc に `:packadd volt` と書いてもらうようにしたいです。

# 理由

これまで Volt はわざわざ vimrc に何も書かなくても使えるように `~/volt/repos/<repos>` から `~/.vim/pack/opt/<repos>` にファイルをコピーしてました。
しかしこの方法だと当然 Volt でインストールするたびにファイルコピーが走って少し待たされることになります。
特に Dropbox で `~/.vim` をまるごと共有してたり、アンチウイルスソフト等がファイル監視してる環境だと遅くなります。

そこでせめてユーザに `:packadd volt` を vimrc に書いてもらうことにしました。
`:packadd volt` によりプラグインのパス (`$VOLTPATH/repos/<repos>`) が rtp に追加され、プラグインの設定 (plugconf) も読み込まれるようになります。

**Comment by tyru** [comment]
@Warashi @thinca ユーザの立場としてこの変更はどう思うのか、意見をお聞きしたいです。

**Comment by tyru** [comment]
ちなみに以前の挙動 (インストール等の度にいちいちファイルをコピーする) も設定ファイル (`$VOLTPATH/config.json`) で選択できるようにする予定です。

**Comment by Warashi** [comment]
profile機能を使うユーザ向けにはマジックコメント同様に自動で追加してあげればいいんじゃないですかね

ところで、`packadd volt`を書くと`$VOLTPATH/repos/<repos>`がrtpに追加されるってのはvolt側で追加するってことですよね？
`.vim/pack/volt/start/system/plugin/bundled_plugconf.vim` でその処理をやるってのはだめなんでしょうか

**Comment by Warashi** [comment]
`bundled_plugconf.vim`と書きましたが、もちろん同ディレクトリの別ファイルでいいです

**Comment by tyru** [comment]
.vim/pack/volt/start/system/plugin/bundled_plugconf.vim で rtp に追加したとしてもプラグインが読み込まれないんです。
具体的には以下のような順番みたいです（もしかしたら 2 と 3 逆かもしれませんが、要するに
 bundled_plugconf.vim でやっても手遅れ）。

1. vimrc の読み込み
1. プラグインの読み込み
1. `~/.vim/pack/*/start/*` の読み込み

**Comment by tyru** [comment]
> profile機能を使うユーザ向けにはマジックコメント同様に自動で追加してあげればいいんじゃないですかね

上述のタイミングの問題があるので、「profile 機能を使うユーザは書かなくてもいい、けど profile 機能を使わないユーザは書かないとダメ」みたいになるので一貫性がないかなーと

**Comment by tyru** [comment]
@rhysd さんに Twitter で「シンボリックリンクじゃ駄目なんでしょうか？」と言われたので、考えた際のメモを載せておきます。
volt build は現在以下の 1 の方法でプラグインを読み込んでいるが、何もわざわざコピーしなくてもいい。
いくつか方法が考えられる。

1. `$VOLTPATH/repos/<repos>` から `~/.vim/pack/volt/opt/<repos>` にコピーする
  * volt build：遅い
  * Vim の起動：速い
2. `~/.vim/pack/volt/opt/<repos>` に symlink を作る
  * volt build：速い
  * Vim の起動：速い
  * 欠点
    * bare リポジトリをサポートできない
    * Windows などサポートできない環境がある
3. `$VOLTPATH/repos/<repos>` を rtp に加えて直接 :source する
  * volt build：速い
  * Vim の起動：遅い
  * 欠点
    * bare リポジトリをサポートできない
    * Vim script でわざわざプラグインのファイルを一つずつ `:source` してるので遅い (はず)
4. vimrc で `:packadd volt` と書いてもらう
  * volt build：速い
  * Vim の起動：速い
  * `~/.vim/pack/volt/start/_volt_started/plugin/started.vim` の行う処理
    * `let g:volt_source_repos = 1`
  * `~/.vim/pack/volt/opt/volt/plugin/startup.vim` の行う処理
    * `g:volt_source_repos` が zero なら以下を行う
      * `set rtp+=$VOLTPATH/repos/<repos>`
      * `autocmd VimEnter * call s:config_xxx()`
    * `g:volt_source_repos` が non-zero なら以下を行う
      * `set rtp+=$VOLTPATH/repos/<repos>`
      * `:so $VOLTPATH/repos/<repos>/plugin/**/*.vim`
      * 警告を出す (`[WARN] Please write "packadd volt" in your vimrc.` `[WARN] Load plugins directly... (very slow)`)
      * `autocmd VimEnter * call s:config_xxx()`

**Comment by Warashi** [comment]
「profile 機能を使うユーザは書かなくてもいい、けど profile 機能を使わないユーザは書かないとダメ」みたいになりますが、`volt profile new`した後に`packadd volt`を書き忘れる事故ガ発生しそうなので自動で書いといて欲しいと思いますね。

**Comment by tyru** [comment]
ふーむ確かにそれもそうですね…

```
{マジックコメント}
packadd volt
{元の }
```

のような内容で `~/.vim/vimrc` をインストールした方が良さそうですね。
すでに `:packadd volt` が `$VOLTPATH/rc/<profile>/vimrc.vim` に書かれてた場合も考慮して、2回 `:packadd volt` が vimrc に書かれていても何もしないようにします。

**Comment by tyru** [comment]
↑のメモを少しだけ更新しました。

> volt build は現在以下の 1 の方法でプラグインを読み込んでいるが、何もわざわざコピーしなくてもいい。
いくつか方法が考えられるが、以下の 4 をデフォルトの動作としたい。
しかし Vim script のトランスパイルを考えた際にトランスパイルした Vim script を読み込むためにコピーした方が嬉しいこともある。
よって今の挙動も後々設定ファイルで選択できるようにする。

**Comment by tyru** [comment]
ref #93

**Comment by Warashi** [comment]
`~/.vim/pack/volt/opt/<repos>` に symlink を作るとbareリポジトリをサポートできないとのことですが、ディレクトリ階層はvoltで作ってやって、各ファイルのsymlinkをつくるようにしてやればできる気がします。
あと、windowsでも`mklink`とかいうsymlinkを作るコマンドがあった気がしますが、それは使えないんですかね？

**Comment by tyru** [comment]
bare リポジトリにはプラグインのファイルはないので、どこかにワークツリーを復元してそこへの symlink を作るという意味でしょうか？
ちなみにもう bare リポジトリをサポートする必要がほぼ無いと思うので、サポートを辞めてもいいかな、とは思っています。

確かに Windows でも mklink を使ったり Win32API を直接呼び出すという手もありそうです。

**Comment by Warashi** [comment]
bare リポジトリの意味をあんまりわからずにコメントしてました。コピーする元があるならそこへのsimlink作れば良いかな、と。よく考えてみるとワークツリーを復元する必要がありそうで面倒ですね。
サポート切ってしまってよいなら切るのも一つの手段だと思います。

**Comment by tyru** [comment]
#157 で `~/.vim/pack/volt/opt` に symlink 貼る実装をしてみて分かったことが2つあります…

* なぜか Windows で `os.Symlink()` を使えないと思い込んでましたが、普通に Windows でも使えました
* `~/.vim/pack/volt/opt/` 以下に symlink を貼っても Vim の package は runtimepath に追加してくれない (無視される)

**Comment by tyru** [comment]
良いニュースがあります！

> `~/.vim/pack/volt/opt/` 以下に symlink を貼っても Vim の package は runtimepath に追加してくれない (無視される)

`~/.vim/pack/volt/start/` じゃないから自動的に読み込まれないだけでした！！！（アホ）

**Comment by tyru** [comment]
すみません、本件は #157 でデフォルトでシンボリックリンクを貼るようにしてとりあえずは速度改善したことと、なるべくならユーザに必要な設定を書かせたくないという理由から、閉じることにします。

ちなみに

* Windows ではジャンクション、それ以外ではシンボリックリンクを使います。
  * @Warashi さんの助言通り `mklink` コマンドを起動するようにしました（[Windows API でジャンクションを作るのはちょっと面倒くさい…](http://www.flexhex.com/docs/articles/hard-links.phtml#junctions)）
* bare リポジトリの場合はシンボリックリンクを作成するのではなく以前通りコピーします。
* `$VOLTPATH/config.toml` に以下のように書くと以前のシンボリックリンクを貼らない挙動に戻ります。

```toml
[build]
strategy = "copy"
```
