### ISSUE TITLE
[volt get -u] Don't change 'repos/trx_id' if no other properties are changed

### ISSUE THREAD

**Issue by tyru** [vim-volt/volt#149]

**Comment by last-partizan** [comment]
Would be great to see this implemented.

It will make storing lockfile in git and syncing better. Any plans for this one?

Looks like this is simple enough issue, maybe i'll try to fix it. However it'll take a time, i have no expirience with go beyond tutorial.

**Comment by tyru** [comment]
Contribution is welcome!
Currently I'm not planning to fix this issue soon, because this is not so annoying for me :p
That's great if you could help fixing this :)

**Comment by last-partizan** [comment]
Nice!
May i ask, why there is need to store that trx_id at all? other package managers, like yarn, don't store anything like that.

**Comment by tyru** [comment]
Well, at first, that property is added because [vim-volt plugin](https://github.com/vim-volt/vim-volt) can detect which plugins are installed/updated.
After that, vim-volt plugin reloads installed/updated plugins to take effect in current Vim, without restarting Vim.

But now, `trx_id` and `repos[].trx_id` are indeed not necessary.
It is for vim-volt plugin, but the plugin can detect it without `trx_id`, such as saving previous hashes and checking updated hashes, and added plugins.

**Comment by last-partizan** [comment]
Great!
I'll take a look.
