### ISSUE TITLE
volt get -l -u will add the plugins to the current profile

### ISSUE THREAD

**Issue by AvianY** [vim-volt/volt#210]
I have just noticed that the commands:
```
volt get -l -u
volt get -u <plugin>
```
will **enable the plugins for the current profile** as well as updating them... Is this the intended behaviour?
I would just like to update all the plugins without anything added to my profile.

**Comment by tyru** [comment]
This is not expected behavior.
duplicate of #197.

**Comment by tyru** [comment]
@AvianY This should be fixed in the latest.
Please see [v0.3.3 changelog](https://github.com/vim-volt/volt/releases/tag/v0.3.3) if you are interested in its detail.
