### ISSUE TITLE
Volt list template example gives hard-to-read output

### ISSUE THREAD

**Issue by AvianY** [vim-volt/volt#224]
The example for volt list is as follows:
`  $ volt list -f '{{ range .Profiles }}{{ if eq $.CurrentProfileName .Name }}{{ range .ReposPath }}{{ . }}{{ end }}{{ end }}{{ end }}'
`
which will print all the plugins for the current profile in a single continous line. I advise the following command replace it:
`
  $ volt list -f '{{ range .Profiles }}{{ if eq $.CurrentProfileName .Name }}{{ range .ReposPath }}{{ println . }}{{ end }}{{ end }}{{ end }}'`

which gives one plugin per line output.

**Comment by tyru** [comment]
Thanks! I'll fix it.
