### ISSUE TITLE
bash completion contribution

### ISSUE THREAD

**Issue by AvianY** [vim-volt/volt#225]
I made a bash script, which adds completion to the volt program.

in general, the script should be put in the $HOME/.bash_completion.d/ directory and sourced from within
the $HOME/.bashrc

For now, everything expected to work, WORKS.
That means:
* Completion of all the subcommands ( profile, migrate, profile add ...)
* Completion of fixed arguments ( migrates arguments )
* Completion of dynamic arguments
so, `volt profile add <TAB>` will complete the profile,
and the `volt profile add default <TAB>` will complete *an installed plugin, not added to default*
and so on for all the other commands. For now the script is limited to plugins prefixed with github.com and
they are completed without the prefix.
[volt.zip](https://github.com/vim-volt/volt/files/1882263/volt.zip)

**Comment by AvianY** [comment]
Yes, I like the end script. I think some edge cases are still not taken care of, but I could fix those soon

**Comment by tyru** [comment]
@AvianY Merged. Thanks!

(I'll create auto-generation scripts of bash/zsh completion functions in the future #199)
