### ISSUE TITLE
Cannot install mattn/emmet-vim

### ISSUE THREAD

**Issue by ishitaku5522** [vim-volt/volt#260]
When I try to install https://github.com/mattn/emmet-vim with volt 0.3.5a on Windows 10, installation failes. Any other plugins have no problem.

go version
```
go version go1.11.2 windows/amd64
```

Command
```
.\volt-v0.3.5a-windows-amd64.exe get mattn/emmet-vim
```
Output
```
[INFO] Full building C:\Users\ishitaku\vimfiles\pack\volt\opt directory ...
[INFO] Installing vimrc and gvimrc ...
! github.com/mattn/emmet-vim > install failed
  * failed to install plugin: entry not found
[ERROR] failed to install some plugins
```

With volt 0.3.4, I got warning, but I could install.
Command
```
.\volt-v0.3.4-windows-amd64.exe get mattn/emmet-vim
```
Output
```
[WARN] failed to clone, try to execute "git clone --recursive https://github.com/mattn/emmet-vim C:\Users\ishitaku\volt\repos\github.com\mattn\emmet-vim" instead...: entry not found
[INFO] Full building C:\Users\ishitaku\vimfiles\pack\volt\opt directory ...
[INFO] Installing vimrc and gvimrc ...
+ github.com/mattn/emmet-vim > installed
```

**Comment by tyru** [comment]
Thanks for the report.
It occurred because the fix #237 was incomplete.
I fixed in `devel` branch. 3ab14bc037082be68aecba7391347529fd65fd88

Please wait the next release, or if you want to try it soon, please run `cd {this repo}; git checkout devel; go install`.

**Comment by ishitaku5522** [comment]
Thank you very much!
I'll try devel branch.

**Comment by tyru** [comment]
Your welcome.
Thanks for the detailed explanation! 😄 

P.S. it's OK to keep this issue open because it's not fixed in master.
I will close this issue at the next release.
