### ISSUE TITLE
"volt edit {repository}" drops {repository}

### ISSUE THREAD

**Issue by mrymtsk** [vim-volt/volt#280]
Newly implemented subcommand "volt edit {repository}" (#278) seems to drop the {repository}.

```sh
$ volt get tyru/caw.vim
[INFO] Full building /Users/Toshiki/.vim/pack/volt/opt directory ...
[INFO] Installing vimrc and gvimrc ...
+ github.com/tyru/caw.vim > installed

$ cat ~/volt/lock.json
{
  "version": 2,
  "current_profile_name": "default",
  "repos": [
    {
      "type": "git",
      "path": "github.com/tyru/caw.vim",
      "version": "98805a60aef339e55e5b917fdb9f69c74e8d8340"
    }
  ],
  "profiles": [
    {
      "name": "default",
      "repos_path": [
        "github.com/tyru/caw.vim"
      ]
    }
  ]
}
$ volt edit tyru/caw.vim
# any edit

$ cat ~/volt/lock.json
{
  "version": 2,
  "current_profile_name": "default",
  "repos": [],
  "profiles": [
    {
      "name": "default",
      "repos_path": []
    }
  ]
}
```

https://github.com/vim-volt/volt/blob/b1c9efdcc7892fc5b48734bfbd73b76a4a1a5911/subcmd/edit.go#L137-L142

Probably this block is related to this issue? If I remove this block and compile volt it works as expected.

**Comment by hupfdule** [comment]
Yes, you are right. That block shouldn't be there. I created a new PR to fix this.

**Comment by mrymtsk** [comment]
Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tyru** [comment]
Thanks for reporting!
I missed that code.
Re-opened this until the fix is merged.
