### ISSUE TITLE
disable sorting alphabetically when running volt build on generated bundled_plugconf.vim

### ISSUE THREAD

**Issue by sabitmaulana** [vim-volt/volt#318]
i want to install [textobj-entire](https://github.com/kana/vim-textobj-entire) plugin that depend on [textobj-user](https://github.com/kana/vim-textobj-user). textobj-user plugin must be added before textobj-entire. but volt build default behavior seems to sort all plugins first before generating bundled_plugconf.vim. When (packadd) sorted, textobj-user will appear under textobj-entire. Hence error occured when opening vim.

is there any way or workaround for this?

**Comment by hupfdule** [comment]
Did you specify `textobj-user` in the plugconf file for `textobj-entire`?
That should actually sort the plugins to be loaded in the correct order.

It should look like this:

```vim
function! s:depends()
  return ['kana/vim-textobject-user']
endfunction
```

**Comment by sabitmaulana** [comment]
Thanks very much!
I'm new to vim and volt. And adding to plugconf works perfectly
