### ISSUE TITLE
'volt get' command overwrites existing plugconf

### ISSUE THREAD

**Issue by Warashi** [vim-volt/volt#75]
ちゃんと伝わる英語を書く自信がないので日本語で書きます。

`volt/lock.json`, `volt/plugconf`, `volt/rc` を他のMacにコピーして `volt get -l` を実行したところ、 `volt/plugconf` 以下のファイルがskeletonで上書きされてしまいました。
ファイルが存在する場合は上書きしないとか、`.vimrc`と同様にマジックコメントで切り替えるとかするべきだと思います。

**Comment by tyru** [comment]
報告ありがとうございます。
ファイルが存在する場合は上書きしないようにします。

**Comment by tyru** [comment]
@Warashi 修正しました！
