### ISSUE TITLE
Update or Delete Gopkg.toml and Gopkg.lock

### ISSUE THREAD

**Issue by Warashi** [vim-volt/volt#83]
Gopkg.tomlやGopkg.lockって使われてますか？
vimlparserのoffsetバグが解決される前のリビジョンになってるので、おそらく使われていないのだと思ってこのIssueを立てています。
使うなら開発中もちゃんとvendoringする、使わないなら紛らわしいので削除する、のどちらかがいいと思います。

**Comment by tyru** [comment]
うおお、すみません…
一応 dep で管理するつもりなので使ってるつもりでした。
パッケージ更新します。
