### ISSUE TITLE
"volt get" failed in clean environment with user vimrc

### ISSUE THREAD

**Issue by thinca** [vim-volt/volt#89]
```
$ rm -fr $VOLTPATH
$ volt get scrooloose/nerdtree
[INFO] Installing github.com/scrooloose/nerdtree ...
[INFO] Installing plugconf github.com/scrooloose/nerdtree ...
[ERROR] could not rebuild /home/thinca/.vim/pack/volt: already exists user vimrc or gvimrc: '/home/thinca/.vim/vimrc' does not have magic comment
```

`/home/thinca/.vim/vimrc` exists as symlink.

**Comment by Warashi** [comment]
[cmd/rebuild.go#L233](https://github.com/vim-volt/volt/blob/master/cmd/rebuild.go#L233)でエラー返してるのが原因ですかね

**Comment by tyru** [comment]
@warashi fixed this. thanks!

**Comment by tyru** [comment]
@thinca この挙動なんですが、やはり revert して元の挙動に戻そうと思ってます。
理由は以下の通りです。 @thinca さんの意見を聞きたいです。

https://github.com/vim-volt/volt/pull/90#issuecomment-352258445

> 私の考えてるケースとしては、$VOLTPATH/rc/<profile>/vimrc.vim にファイルがある (=~/.vim/vimrc にインストールされることを意図している) のに、 volt build を実行した後で ~/.vim/vimrc にインストールされていないと vimrc が反映されてない！となってハマることもあるかなーと思いました。
> warning を出すというのも考えたのですが、どうせならエラー終了してしまった方が気付きやすいかなーと。
> どちらにしろ警告もなしにスキップする現在の挙動は変えたいと思ってます。

**Comment by Warashi** [comment]
つまり、デフォルトの設定では既存のvimrcとは共存できない形になると言うことですかね？
`$VOLTPATH/rc/<profile>/vimrc.vim` にファイルがあるかどうか確かめて分岐させるあたりが落としどころかなと思いますが。

**Comment by tyru** [comment]
はい。
現在の挙動としてはマジックコメントを持たない既存の `~/.vim/vimrc` または `~/.vim/gvimrc` が存在する場合、常に 
* `$VOLTPATH/rc/<profile>/vimrc.vim`
* `$VOLTPATH/rc/<profile>/gvimrc.vim
は `~/.vim/` にコピーされず無視されます。
profile 機能の意図としては vimrc, gvimrc, プラグインの一覧をセットで切り替えるので、 `$VOLTPATH/rc/<profile>/` にある vimrc, gvimrc がインストールされないのは機能として欠陥であるという判断です。
なので常に既存の vimrc を使ってほしい人は`$VOLTPATH/rc/<profile>/` に vimrc,gvimrc を置かなければ良いと思ってるのですが、どうでしょうか？

**Comment by tyru** [comment]
つまり、profile 機能を使わない人は今まで通り `~/.vim/vimrc` などに置いて、profile 機能を使う人は `$VOLTPATH/rc/<profile>/vimrc` に置く、というのを想定してます。

**Comment by Warashi** [comment]
`$VOLTPATH/rc/<profile>/` に vimrc, gvimrc を置かなければいいというのは同意します。
このIssueはもともと空の`$VOLTPATH`で`volt get`した場合にマジックコメントのない`.vim/vimrc`を見つけて落ちるという挙動がおかしいという主旨のはずですね？
それを、とりあえずマジックコメントを持たない既存のファイルが存在する場合にスキップするという処理に変えたのが問題だという話ですね。

**Comment by tyru** [comment]
あっ…そうです。
なので「revert して元の挙動に戻す」は間違いすね、すみませんorz

新しい挙動（仕様）は

* 以下 `$VOLTPATH/rc/<profile>/` にある vimrc,gvimrc を profile vimrc, profile gvimrc と呼ぶ
* 以下 `~/.vim/` にある vimrc,gvimrc を user vimrc, user gvimrc と呼ぶ
* A = profile vimrc か profile gvimrc が存在する
* B = user vimrc か user gvimrc が存在する

とすると、

* A & B の時 = エラー
* A & !B の時 = profile vimrc/gvimrc がインストールされる (profile 機能を使うユーザーのケース)
* !A & B の時 = 何もしない、よって user vimrc/gvimrc はそのまま (profile 機能を使わないユーザーのケース)
* !A & !B の時 = 何もしない

という感じです。

**Comment by Warashi** [comment]
大体良いと思います。
特定のprofileにおいてvimrc, gvimrcが存在しない場合にはマジックコメントのあるvimrc, gvimrcは削除するという想定でいいですか？

**Comment by tyru** [comment]
あーその通りです！追記しました。

**Comment by tyru** [comment]
返ったら #117 で実装次第マージします（テストコードも含めてなので今日中にできるか分かりませんが）。

**Comment by tyru** [comment]
テストするケースは以下の4つです。

* A & !B
  * if profile vimrc/gvimrc exists, it's installed to `~/.vim/{vimrc,gvimrc}`
  * if profile vimrc/gvimrc does not exist, it's removed from `~/.vim/{vimrc,gvimrc}`
  * (the case for the users of profile feature)

* B & C
  * if A: error
  * user vimrc/gvimrc are not changed
  * (the case for the non-users of profile feature)

* B & !C
  * if A: user vimrc/gvimrc are installed to `~/.vim/{vimrc,gvimrc}`
  * if !A: user vimrc/gvimrc are removed
  * (the case for the users of profile feature)

* !A & !B
  * no vimrc/gvimrc are installed to `~/.vim/{vimrc,gvimrc}`

**Comment by tyru** [comment]
#117 をマージしました。
